### Default ###
stages:
  - build
  - test
  - deliver
  - finish

# Standard job image
image: gitlab.sdu.dk:5050/semester-project-e2021/team-12/ci-cd/base_image:0.0.2

### Rules ###
# Trigger rules
.default:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_CD_DEVELOPMENT_BRANCH'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == $CI_CD_DEVELOPMENT_BRANCH'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ /^$CI_CD_RELEASE_BRANCH/'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ /^$CI_CD_HOTFIX_BRANCH/'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_CD_PRODUCTION_BRANCH'
      when: on_success

.merge_request_production_branch:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_CD_PRODUCTION_BRANCH'
      when: on_success

.merge_production:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_BUILD_REF_NAME == $CI_CD_PRODUCTION_BRANCH'
      when: on_success

.always:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_CD_DEVELOPMENT_BRANCH'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == $CI_CD_DEVELOPMENT_BRANCH'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ /^$CI_CD_RELEASE_BRANCH/'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ /^$CI_CD_HOTFIX_BRANCH/'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_CD_PRODUCTION_BRANCH'
      when: always

.always_except_merge_production:
  rules:1
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_CD_DEVELOPMENT_BRANCH'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == $CI_CD_DEVELOPMENT_BRANCH'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ /^$CI_CD_RELEASE_BRANCH/'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ /^$CI_CD_HOTFIX_BRANCH/'
      when: always

.on_failure:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_CD_DEVELOPMENT_BRANCH'
      when: on_failure
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == $CI_CD_DEVELOPMENT_BRANCH'
      when: on_failure
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ /^$CI_CD_RELEASE_BRANCH/'
      when: on_failure
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ /^$CI_CD_HOTFIX_BRANCH/'
      when: on_failure
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_CD_PRODUCTION_BRANCH'
      when: on_failure

# Jobs rules
.build:
  stage: build
  extends: .default

.build_production:
  stage: build
  extends: .merge_request_production_branch

.unit:
  stage: test
  extends: .default

.acceptance:
  stage: test
  extends: .merge_request_production_branch

.integration:
  stage: test
  extends: .merge_request_production_branch

.performance:
  stage: test
  extends: .merge_request_production_branch

.deliver:
  stage: deliver
  extends: .merge_production

.finish:
  stage: finish
  extends: .always_merge_production

### Methods ###
.test_image:
  # Variables
  #
  # CI_CD_IMAGE_NAME: (string)
  #   Required
  # CI_CD_PATH: (string)
  #   Default: .
  # CI_CD_FILE_NAME: (string)
  #   Default: Dockerfile
  #
  image: gitlab.sdu.dk:5050/semester-project-e2021/team-12/ci-cd/docker:0.0.3
  services:
    - docker:dind
  script:
    - ci_cd_tool test create

.remove_test_image:
  # Variable
  #
  # CI_CD_IMAGE_NAME: (string)
  #   Required
  #
  image: gitlab.sdu.dk:5050/semester-project-e2021/team-12/ci-cd/docker:0.0.3
  services:
    - docker:dind
  script:
    - ci_cd_tool test remove

.production_image:
  # Variable
  #
  # CI_CD_IMAGE_NAME: (string)
  #   Required
  #
  image: gitlab.sdu.dk:5050/semester-project-e2021/team-12/ci-cd/docker:0.0.3
  services:
    - docker:dind
  script:
    - ci_cd_tool production

.artifact:
  artifacts:
    expose_as: "Artifact"
    name: "branch-${CI_COMMIT_REF_NAME}-commit-${CI_COMMIT_SHORT_SHA}"
    paths:
      - ${CI_BUILDS_DIR}
    expire_in: 3 hrs

### Jobs ###
build:check_request_title:
  extends:
    - .build
    - .merge_request_production_branch
  script:
    - ci_cd_tool version

finish:failure:
  extends:
    .finish
    .on_failure
    .artifact
  script: echo "Create artifact"
  artifacts:
    expose_as: "Failure Artifact"
    expire_in: 8 hrs
