stages:
  - build

temporary_job:
  stage: build
  image: alpine:3.13
  script:
    - echo "This is temporary"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "main"'
      when: on_success
